# Generated by Django 4.2.4 on 2023-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimage',
            name='create',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='upimage',
            name='expire',
            field=models.DateField(null=True),
        ),
    ]
