# Generated by Django 4.2.4 on 2023-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_upimage_create_upimage_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upimage',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
