# Generated by Django 4.2.4 on 2023-08-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_upimage_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upimage',
            options={'ordering': ['-published']},
        ),
    ]
