# Generated by Django 4.2.4 on 2023-08-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0003_alter_upimage_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upimage',
            old_name='create',
            new_name='created',
        ),
    ]
