# Generated by Django 4.2.4 on 2023-08-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
