# Generated by Django 4.2.4 on 2023-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_sub_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
